service: aws-rnative-bot

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-3

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.vk
    cors: true
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
